In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/kobe_career_stats.csv")

df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,977,1996-97,0,1610612747,LAL,18.0,71,6,1102,176,...,0.819,47,85,132,91,49,23,112,102,539
1,977,1997-98,0,1610612747,LAL,19.0,79,1,2056,391,...,0.794,79,163,242,199,74,40,157,180,1220
2,977,1998-99,0,1610612747,LAL,20.0,50,50,1896,362,...,0.839,53,211,264,190,72,50,157,153,996
3,977,1999-00,0,1610612747,LAL,21.0,66,62,2524,554,...,0.821,108,308,416,323,106,62,182,220,1485
4,977,2000-01,0,1610612747,LAL,22.0,68,68,2783,701,...,0.853,104,295,399,338,114,43,220,222,1938

In [3]:
df.shape

(20, 27)

In [4]:
df.columns.tolist()

['PLAYER_ID',
 'SEASON_ID',
 'LEAGUE_ID',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'PLAYER_AGE',
 'GP',
 'GS',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          20 non-null     int64
 1   SEASON_ID          20 non-null     str
 2   LEAGUE_ID          20 non-null     int64
 3   TEAM_ID            20 non-null     int64
 4   TEAM_ABBREVIATION  20 non-null     str
 5   PLAYER_AGE         20 non-null     float64
 6   GP                 20 non-null     int64
 7   GS                 20 non-null     int64
 8   MIN                20 non-null     int64
 9   FGM                20 non-null     int64
 10  FGA                20 non-null     int64
 11  FG_PCT             20 non-null     float64
 12  FG3M               20 non-null     int64
 13  FG3A               20 non-null     int64
 14  FG3_PCT            20 non-null     float64
 15  FTM                20 non-null     int64
 16  FTA                20 non-null     int64
 17  FT_PCT             20 non-null     float64
 18  OREB               20 non-null     int64
 19  DREB               20 non-null     int64
 20  REB                20 non-null     int64
 21  AST                20 non-null     int64
 22  STL                20 non-null     int64
 23  BLK                20 non-null     int64
 24  TOV                20 non-null     int64
 25  PF                 20 non-null     int64
 26  PTS                20 non-null     int64
dtypes: float64(4), int64(21), str(2)
memory usage: 4.3 KB

In [6]:
df["MPG"] = df["MIN"] / df["GP"]

df["PPG"] = df["PTS"] / df["GP"]
df["APG"] = df["AST"] / df["GP"]
df["RPG"] = df["REB"] / df["GP"]
df["SPG"] = df["STL"] / df["GP"]
df["BPG"] = df["BLK"] / df["GP"]
df["TOPG"] = df["TOV"] / df["GP"]

df["TS_PCT"] = df["PTS"] / (
    2 * (df["FGA"] + 0.44 * df["FTA"])
)

df["EFG_PCT"] = (
    df["FGM"] + 0.5 * df["FG3M"]
) / df["FGA"]

df["THREE_PA_RATE"] = df["FG3A"] / df["FGA"]

df["FTA_RATE"] = df["FTA"] / df["FGA"]

In [7]:
career_view = df[
    [
        "SEASON_ID",
        "PLAYER_AGE",
        "GP",
        "MPG",
        "PPG",
        "APG",
        "RPG",
        "SPG",
        "BPG",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT",
        "TS_PCT",
        "EFG_PCT",
        "THREE_PA_RATE",
        "FTA_RATE"
    ]
].copy()

career_view.round(3)

,SEASON_ID,PLAYER_AGE,GP,MPG,PPG,APG,RPG,SPG,BPG,FG_PCT,FG3_PCT,FT_PCT,TS_PCT,EFG_PCT,THREE_PA_RATE,FTA_RATE
0,1996-97,18.0,71,15.521,7.592,1.282,1.859,0.690,0.324,0.417,0.375,0.819,0.544,0.477,0.322,0.393
1,1997-98,19.0,79,26.025,15.443,2.519,3.063,0.937,0.506,0.428,0.341,0.794,0.548,0.469,0.241,0.501
2,1998-99,20.0,50,37.920,19.920,3.800,5.280,1.440,1.000,0.465,0.267,0.839,0.549,0.482,0.130,0.375
3,1999-00,21.0,66,38.242,22.500,4.894,6.303,1.606,0.939,0.468,0.319,0.821,0.546,0.488,0.122,0.341
4,2000-01,22.0,68,40.926,28.500,4.971,5.868,1.676,0.632,0.464,0.305,0.853,0.552,0.484,0.132,0.369
5,2001-02,23.0,80,38.312,25.238,5.475,5.512,1.475,0.438,0.469,0.250,0.829,0.544,0.479,0.083,0.369
6,2002-03,24.0,82,41.476,30.012,5.866,6.878,2.207,0.817,0.451,0.383,0.843,0.550,0.483,0.168,0.371
7,2003-04,25.0,65,37.723,23.954,5.077,5.523,1.723,0.431,0.438,0.327,0.852,0.551,0.468,0.184,0.452
8,2004-05,26.0,66,40.742,27.561,6.030,5.939,1.303,0.803,0.433,0.339,0.816,0.563,0.482,0.292,0.502
9,2005-06,27.0,80,40.962,35.400,4.500,5.312,1.838,0.375,0.450,0.347,0.850,0.559,0.491,0.238,0.377
10,2006-07,28.0,77,40.779,31.558,5.364,5.701,1.442,0.468,0.463,0.344,0.868,0.580,0.502,0.227,0.437
11,2007-08,29.0,82,38.927,28.329,5.378,6.305,1.841,0.488,0.459,0.361,0.840,0.576,0.503,0.246,0.439
12,2008-09,30.0,82,36.098,26.841,4.866,5.232,1.463,0.451,0.467,0.351,0.856,0.561,0.502,0.196,0.329
13,2009-10,31.0,73,38.836,26.986,5.000,5.356,1.548,0.274,0.456,0.329,0.811,0.545,0.488,0.192,0.345
14,2010-11,32.0,82,33.890,25.341,4.732,5.110,1.207,0.146,0.451,0.323,0.828,0.548,0.487,0.217,0.356
15,2011-12,33.0,58,38.483,27.862,4.552,5.397,1.190,0.310,0.430,0.303,0.845,0.527,0.462,0.215,0.338
16,2012-13,34.0,78,38.628,27.346,6.013,5.551,1.359,0.321,0.463,0.324,0.839,0.570,0.504,0.255,0.392
17,2013-14,35.0,6,29.500,13.833,6.333,4.333,1.167,0.167,0.425,0.188,0.857,0.505,0.445,0.219,0.288
18,2014-15,36.0,35,34.486,22.343,5.629,5.686,1.343,0.200,0.373,0.293,0.813,0.477,0.411,0.258,0.338
19,2015-16,37.0,66,28.227,17.591,2.788,3.742,0.939,0.197,0.358,0.285,0.826,0.469,0.417,0.420,0.252

In [8]:
career_view = df[
    [
        "SEASON_ID",
        "PLAYER_AGE",
        "GP",
        "MPG",
        "PPG",
        "APG",
        "RPG",
        "SPG",
        "BPG",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT",
        "TS_PCT",
        "EFG_PCT",
        "THREE_PA_RATE",
        "FTA_RATE"
    ]
].copy()

career_view.round(3)

,SEASON_ID,PLAYER_AGE,GP,MPG,PPG,APG,RPG,SPG,BPG,FG_PCT,FG3_PCT,FT_PCT,TS_PCT,EFG_PCT,THREE_PA_RATE,FTA_RATE
0,1996-97,18.0,71,15.521,7.592,1.282,1.859,0.690,0.324,0.417,0.375,0.819,0.544,0.477,0.322,0.393
1,1997-98,19.0,79,26.025,15.443,2.519,3.063,0.937,0.506,0.428,0.341,0.794,0.548,0.469,0.241,0.501
2,1998-99,20.0,50,37.920,19.920,3.800,5.280,1.440,1.000,0.465,0.267,0.839,0.549,0.482,0.130,0.375
3,1999-00,21.0,66,38.242,22.500,4.894,6.303,1.606,0.939,0.468,0.319,0.821,0.546,0.488,0.122,0.341
4,2000-01,22.0,68,40.926,28.500,4.971,5.868,1.676,0.632,0.464,0.305,0.853,0.552,0.484,0.132,0.369
5,2001-02,23.0,80,38.312,25.238,5.475,5.512,1.475,0.438,0.469,0.250,0.829,0.544,0.479,0.083,0.369
6,2002-03,24.0,82,41.476,30.012,5.866,6.878,2.207,0.817,0.451,0.383,0.843,0.550,0.483,0.168,0.371
7,2003-04,25.0,65,37.723,23.954,5.077,5.523,1.723,0.431,0.438,0.327,0.852,0.551,0.468,0.184,0.452
8,2004-05,26.0,66,40.742,27.561,6.030,5.939,1.303,0.803,0.433,0.339,0.816,0.563,0.482,0.292,0.502
9,2005-06,27.0,80,40.962,35.400,4.500,5.312,1.838,0.375,0.450,0.347,0.850,0.559,0.491,0.238,0.377
10,2006-07,28.0,77,40.779,31.558,5.364,5.701,1.442,0.468,0.463,0.344,0.868,0.580,0.502,0.227,0.437
11,2007-08,29.0,82,38.927,28.329,5.378,6.305,1.841,0.488,0.459,0.361,0.840,0.576,0.503,0.246,0.439
12,2008-09,30.0,82,36.098,26.841,4.866,5.232,1.463,0.451,0.467,0.351,0.856,0.561,0.502,0.196,0.329
13,2009-10,31.0,73,38.836,26.986,5.000,5.356,1.548,0.274,0.456,0.329,0.811,0.545,0.488,0.192,0.345
14,2010-11,32.0,82,33.890,25.341,4.732,5.110,1.207,0.146,0.451,0.323,0.828,0.548,0.487,0.217,0.356
15,2011-12,33.0,58,38.483,27.862,4.552,5.397,1.190,0.310,0.430,0.303,0.845,0.527,0.462,0.215,0.338
16,2012-13,34.0,78,38.628,27.346,6.013,5.551,1.359,0.321,0.463,0.324,0.839,0.570,0.504,0.255,0.392
17,2013-14,35.0,6,29.500,13.833,6.333,4.333,1.167,0.167,0.425,0.188,0.857,0.505,0.445,0.219,0.288
18,2014-15,36.0,35,34.486,22.343,5.629,5.686,1.343,0.200,0.373,0.293,0.813,0.477,0.411,0.258,0.338
19,2015-16,37.0,66,28.227,17.591,2.788,3.742,0.939,0.197,0.358,0.285,0.826,0.469,0.417,0.420,0.252

In [16]:
# Kobe career reference values
total_gp = df["GP"].sum()

kobe_reference = {
    "MPG": df["MIN"].sum() / total_gp,
    "PPG": df["PTS"].sum() / total_gp,
    "APG": df["AST"].sum() / total_gp,
    "RPG": df["REB"].sum() / total_gp,
    "SPG": df["STL"].sum() / total_gp,
    "BPG": df["BLK"].sum() / total_gp,
    "TOPG": df["TOV"].sum() / total_gp,

    "FG_PCT": df["FGM"].sum() / df["FGA"].sum(),
    "FG3_PCT": df["FG3M"].sum() / df["FG3A"].sum(),
    "FT_PCT": df["FTM"].sum() / df["FTA"].sum(),

    "TS_PCT": df["PTS"].sum() / (
        2 * (df["FGA"].sum() + 0.44 * df["FTA"].sum())
    ),

    "EFG_PCT": (
        df["FGM"].sum() + 0.5 * df["FG3M"].sum()
    ) / df["FGA"].sum(),

    "THREE_PA_RATE": df["FG3A"].sum() / df["FGA"].sum(),
    "FTA_RATE": df["FTA"].sum() / df["FGA"].sum()
}

kobe_reference

{'MPG': np.float64(36.13893016344725),
 'PPG': np.float64(24.994799405646358),
 'APG': np.float64(4.684992570579495),
 'RPG': np.float64(5.235512630014859),
 'SPG': np.float64(1.4442793462109955),
 'BPG': np.float64(0.475482912332838),
 'TOPG': np.float64(2.9791976225854384),
 'FG_PCT': np.float64(0.44729007633587786),
 'FG3_PCT': np.float64(0.3294266137756942),
 'FT_PCT': np.float64(0.8368794326241135),
 'TS_PCT': np.float64(0.5496352864448891),
 'EFG_PCT': np.float64(0.48215648854961835),
 'THREE_PA_RATE': np.float64(0.2116793893129771),
 'FTA_RATE': np.float64(0.38209923664122136)}

In [19]:
def similarity_score(reference, candidate):
    if reference == 0:
        return 100 if candidate == 0 else 0

    difference = abs(candidate - reference)
    percentage_difference = difference / abs(reference)

    return max(0, 100 * (1 - percentage_difference))

In [ ]:
similarity_score(7.67, 7.37)

96.08865710560626

In [31]:
candidate_names = [
    "Shai Gilgeous-Alexander",
    "Luka Doncic",
    "Anthony Edwards",
    "Devin Booker",
    "Jalen Brunson",
    "Jaylen Brown",
    "Jayson Tatum",
    "Kevin Durant",
    "Kawhi Leonard",
    "Jimmy Butler",
    "LeBron James",
    "Donovan Mitchell",
    "Ja Morant",
    "De'Aaron Fox",
    "Tyrese Maxey",
    "Cade Cunningham",
    "Trae Young",
    "Jamal Murray",
    "Stephen Curry",
    "Nikola Jokic",
    "LaMelo Ball",
    "Darius Garland",
    "Jalen Williams",
    "Desmond Bane",
    "Brandon Ingram",
    "Mikal Bridges",
    "OG Anunoby",
    "RJ Barrett",
    "Scottie Barnes",
    "Paolo Banchero",
    "Franz Wagner",
    "Jalen Johnson",
    "Julius Randle",
    "Deni Avdija",
    "Brandon Miller",
    "Cam Thomas",
    "Anfernee Simons",
    "Jordan Poole",
    "Tyler Herro",
    "Dejounte Murray",
    "CJ McCollum",
    "DeMar DeRozan",
    "Michael Porter Jr.",
    "Zach LaVine",
    "Norman Powell",
    "Bradley Beal",
    "Khris Middleton",
    "Andrew Wiggins",
    "Aaron Gordon",
    "Jerami Grant",
    "Miles Bridges",
    "Trey Murphy III",
    "Jaden McDaniels",
    "Austin Reaves",
    "Collin Sexton",
    "Jordan Clarkson",
    "Buddy Hield",
    "Klay Thompson",
    "Harrison Barnes",
    "Zion Williamson",
    "Pascal Siakam",
    "Lauri Markkanen",
    "Chet Holmgren",
    "Bam Adebayo",
    "Paul George",
    "Jrue Holiday",
    "Jalen Green",
    "Amen Thompson",
    "Devin Vassell",
    "Victor Wembanyama"
]

len(candidate_names)

70

In [32]:
from nba_api.stats.static import players

candidate_records = []

for name in candidate_names:
    matches = players.find_players_by_full_name(name)

    if matches:
        player = matches[0]

        candidate_records.append({
            "PLAYER_ID": player["id"],
            "PLAYER_NAME": player["full_name"]
        })
    else:
        print("NOT FOUND:", name)

candidate_pool = pd.DataFrame(candidate_records)

candidate_pool

    PLAYER_ID              PLAYER_NAME
0     1628983  Shai Gilgeous-Alexander
1     1629029              Luka Dončić
2     1630162          Anthony Edwards
3     1626164             Devin Booker
4     1628973            Jalen Brunson
..        ...                      ...
65     201950             Jrue Holiday
66    1630224              Jalen Green
67    1641708            Amen Thompson
68    1630170            Devin Vassell
69    1641705        Victor Wembanyama

[70 rows x 2 columns]

In [33]:
candidate_pool.shape

(70, 2)

In [34]:
from pathlib import Path

output_path = Path("../data/manual/candidate_pool.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

candidate_pool.to_csv(output_path, index=False)

print(f"Saved candidate pool to: {output_path}")

Saved candidate pool to: ..\data\manual\candidate_pool.csv

In [35]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
).get_data_frames()[0]

candidate_stats = stats[
    stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

candidate_stats[
    [
        "PLAYER_NAME",
        "GP",
        "MIN",
        "PTS",
        "AST",
        "REB",
        "STL",
        "BLK",
        "TOV",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT"
    ]
].sort_values("PTS", ascending=False)

,PLAYER_NAME,GP,MIN,PTS,AST,REB,STL,BLK,TOV,FG_PCT,FG3_PCT,FT_PCT
372,Luka Dončić,64,35.8,33.5,8.3,7.7,1.6,0.5,4.0,0.476,0.366,0.780
501,Shai Gilgeous-Alexander,68,33.2,31.1,6.6,4.3,1.4,0.8,2.2,0.553,0.386,0.879
31,Anthony Edwards,61,35.0,28.8,3.7,5.0,1.4,0.8,2.9,0.489,0.399,0.796
260,Jaylen Brown,71,34.4,28.7,5.1,6.9,1.0,0.4,3.6,0.477,0.347,0.795
554,Tyrese Maxey,70,38.0,28.3,6.6,4.1,1.9,0.8,2.4,0.462,0.367,0.892
...,...,...,...,...,...,...,...,...,...,...,...,...
341,Khris Middleton,63,22.8,10.2,2.8,3.7,0.7,0.1,1.7,0.420,0.360,0.875
194,Harrison Barnes,77,25.8,9.9,1.9,2.8,0.6,0.2,0.8,0.456,0.388,0.829
291,Jordan Clarkson,72,17.8,8.6,1.3,1.8,0.4,0.1,0.9,0.451,0.327,0.830
53,Bradley Beal,6,20.2,8.2,1.7,0.8,0.5,0.0,1.5,0.375,0.368,0.750
68,Buddy Hield,51,16.1,7.6,1.4,2.3,0.8,0.2,0.9,0.437,0.349,0.811

In [36]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
).get_data_frames()[0]

candidate_stats = stats[
    stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

candidate_stats[
    [
        "PLAYER_NAME",
        "GP",
        "MIN",
        "PTS",
        "AST",
        "REB",
        "STL",
        "BLK",
        "TOV",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT"
    ]
].sort_values("PTS", ascending=False)

,PLAYER_NAME,GP,MIN,PTS,AST,REB,STL,BLK,TOV,FG_PCT,FG3_PCT,FT_PCT
372,Luka Dončić,64,35.8,33.5,8.3,7.7,1.6,0.5,4.0,0.476,0.366,0.780
501,Shai Gilgeous-Alexander,68,33.2,31.1,6.6,4.3,1.4,0.8,2.2,0.553,0.386,0.879
31,Anthony Edwards,61,35.0,28.8,3.7,5.0,1.4,0.8,2.9,0.489,0.399,0.796
260,Jaylen Brown,71,34.4,28.7,5.1,6.9,1.0,0.4,3.6,0.477,0.347,0.795
554,Tyrese Maxey,70,38.0,28.3,6.6,4.1,1.9,0.8,2.4,0.462,0.367,0.892
...,...,...,...,...,...,...,...,...,...,...,...,...
341,Khris Middleton,63,22.8,10.2,2.8,3.7,0.7,0.1,1.7,0.420,0.360,0.875
194,Harrison Barnes,77,25.8,9.9,1.9,2.8,0.6,0.2,0.8,0.456,0.388,0.829
291,Jordan Clarkson,72,17.8,8.6,1.3,1.8,0.4,0.1,0.9,0.451,0.327,0.830
53,Bradley Beal,6,20.2,8.2,1.7,0.8,0.5,0.0,1.5,0.375,0.368,0.750
68,Buddy Hield,51,16.1,7.6,1.4,2.3,0.8,0.2,0.9,0.437,0.349,0.811

In [37]:
candidate_stats["TS_PCT"] = candidate_stats["PTS"] / (
    2 * (
        candidate_stats["FGA"]
        + 0.44 * candidate_stats["FTA"]
    )
)

candidate_stats["EFG_PCT"] = (
    candidate_stats["FGM"]
    + 0.5 * candidate_stats["FG3M"]
) / candidate_stats["FGA"]

candidate_stats["THREE_PA_RATE"] = (
    candidate_stats["FG3A"] / candidate_stats["FGA"]
)

candidate_stats["FTA_RATE"] = (
    candidate_stats["FTA"] / candidate_stats["FGA"]
)

candidate_stats[
    [
        "PLAYER_NAME",
        "PTS",
        "AST",
        "REB",
        "TS_PCT",
        "EFG_PCT",
        "THREE_PA_RATE",
        "FTA_RATE"
    ]
].round(3)

,PLAYER_NAME,PTS,AST,REB,TS_PCT,EFG_PCT,THREE_PA_RATE,FTA_RATE
3,Aaron Gordon,16.2,2.7,5.8,0.619,0.572,0.396,0.405
21,Amen Thompson,18.3,5.3,7.8,0.596,0.549,0.114,0.371
27,Andrew Wiggins,15.4,2.7,4.8,0.585,0.554,0.405,0.198
28,Anfernee Simons,14.3,2.4,2.5,0.576,0.555,0.585,0.119
31,Anthony Edwards,28.8,3.7,5.0,0.616,0.574,0.416,0.356
...,...,...,...,...,...,...,...,...
550,Tyler Herro,20.5,4.1,4.8,0.601,0.561,0.429,0.212
554,Tyrese Maxey,28.3,6.6,4.1,0.589,0.535,0.402,0.280
559,Victor Wembanyama,25.0,3.1,11.5,0.626,0.565,0.325,0.414
577,Zach LaVine,19.2,2.3,2.8,0.616,0.568,0.464,0.257
580,Zion Williamson,21.0,3.2,5.7,0.644,0.600,0.008,0.577

In [38]:
output_path = Path("../data/processed/candidate_traditional_stats_2025_26.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

candidate_stats.to_csv(output_path, index=False)

print(f"Saved stats to: {output_path}")

Saved stats to: ..\data\processed\candidate_traditional_stats_2025_26.csv

In [39]:
candidate_stats.shape

(70, 73)

In [42]:
%pip install lxml

Requirement already satisfied: lxml in c:\Users\sachi\Documents\Aryan\kobe-similarity-project\kobe-similarity-analysis\.venv\Lib\site-packages (6.1.3)
Note: you may need to restart the kernel to use updated packages.

In [45]:
import pandas as pd

crafted_tables = pd.read_html(
    "https://craftednba.com/player-stats"
)

print("Number of tables:", len(crafted_tables))

for i, table in enumerate(crafted_tables):
    print("\nTABLE", i)
    print("Shape:", table.shape)
    print("Columns:")
    print(table.columns.tolist())

HTTPError: HTTP Error 403: Forbidden

In [44]:
import requests
import pandas as pd
from io import StringIO

url = "https://craftednba.com/player-stats"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/153.0.0.0 Safari/537.36"
    )
}

response = requests.get(url, headers=headers, timeout=30)

print("Status code:", response.status_code)

crafted_tables = pd.read_html(StringIO(response.text))

print("Number of tables:", len(crafted_tables))

for i, table in enumerate(crafted_tables):
    print("\nTABLE", i)
    print("Shape:", table.shape)
    print(table.columns.tolist())

Status code: 200
Number of tables: 1

TABLE 0
Shape: (575, 23)
[('Unnamed: 0_level_0', '#'), ('Unnamed: 1_level_0', 'Name'), ('Unnamed: 2_level_0', 'Age'), ('Traditional', 'MP'), ('Traditional', 'GP'), ('Traditional', 'MPG'), ('Traditional', 'FGM'), ('Traditional', 'FGA'), ('Traditional', 'FG%'), ('Traditional', '3PM'), ('Traditional', '3PA'), ('Traditional', '3P%'), ('Traditional', 'FTM'), ('Traditional', 'FTA'), ('Traditional', 'FT%'), ('Traditional', 'ORB'), ('Traditional', 'DRB'), ('Traditional', 'REB'), ('Traditional', 'AST'), ('Traditional', 'STL'), ('Traditional', 'BLK'), ('Traditional', 'TOV'), ('Traditional', 'PTS')]

In [46]:
candidate_records = []

for name in candidate_names:
    matches = players.find_players_by_full_name(name)

    if matches:
        player = matches[0]

        candidate_records.append({
            "PLAYER_ID": player["id"],
            "PLAYER_NAME": player["full_name"]
        })
    else:
        print("NOT FOUND:", name)

candidate_pool = pd.DataFrame(candidate_records)

print(candidate_pool.shape)

(70, 2)

In [47]:
kobe_reference_df = pd.DataFrame(
    [kobe_reference]
).T.reset_index()

kobe_reference_df.columns = ["Metric", "Kobe_Value"]

kobe_reference_df.round(3)

           Metric  Kobe_Value
0             MPG      36.139
1             PPG      24.995
2             APG       4.685
3             RPG       5.236
4             SPG       1.444
5             BPG       0.475
6            TOPG       2.979
7          FG_PCT       0.447
8         FG3_PCT       0.329
9          FT_PCT       0.837
10         TS_PCT       0.550
11        EFG_PCT       0.482
12  THREE_PA_RATE       0.212
13       FTA_RATE       0.382

In [48]:
comparison_metrics = [
    "PTS",
    "AST",
    "REB",
    "STL",
    "BLK",
    "TOV",
    "FG_PCT",
    "FG3_PCT",
    "FT_PCT",
    "TS_PCT",
    "EFG_PCT",
    "THREE_PA_RATE",
    "FTA_RATE"
]

for metric in comparison_metrics:
    if metric in candidate_stats.columns and metric in kobe_reference:
        candidate_stats[f"{metric}_SIM"] = candidate_stats[metric].apply(
            lambda x: similarity_score(kobe_reference[metric], x)
        )

candidate_stats[
    ["PLAYER_NAME"] +
    [f"{m}_SIM" for m in comparison_metrics if f"{m}_SIM" in candidate_stats.columns]
].head()

,PLAYER_NAME,FG_PCT_SIM,FG3_PCT_SIM,FT_PCT_SIM,TS_PCT_SIM,EFG_PCT_SIM,THREE_PA_RATE_SIM,FTA_RATE_SIM
3,Aaron Gordon,88.886424,81.916037,91.650000,87.331460,81.351369,12.737368,93.900493
21,Amen Thompson,80.614387,65.568473,93.083898,91.590240,86.086273,53.683244,97.150710
27,Andrew Wiggins,93.804932,74.327094,93.681356,93.514064,85.157823,8.692439,51.909841
28,Anfernee Simons,98.370168,83.130268,92.935593,95.226915,84.874567,0.000000,31.050590
31,Anthony Edwards,90.674972,78.880460,95.115254,87.884324,80.898123,3.551217,93.283527

In [49]:
similarity_columns = [
    f"{m}_SIM"
    for m in comparison_metrics
    if f"{m}_SIM" in candidate_stats.columns
]

candidate_stats["TRADITIONAL_SIMILARITY"] = (
    candidate_stats[similarity_columns].mean(axis=1)
)

candidate_stats[
    ["PLAYER_NAME", "TRADITIONAL_SIMILARITY"]
].sort_values(
    "TRADITIONAL_SIMILARITY",
    ascending=False
).head(10)

         PLAYER_NAME  TRADITIONAL_SIMILARITY
178     Franz Wagner               90.981042
260     Jaylen Brown               90.856029
239   Jalen Williams               90.166134
454   Paolo Banchero               90.121196
310    Julius Randle               89.376946
135    DeMar DeRozan               89.106131
496   Scottie Barnes               88.965677
146     Devin Booker               88.889144
71   Cade Cunningham               88.626996
455    Pascal Siakam               88.567516